config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/" => "home#index"

  resources :todos
  resources :users

  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signin" => "sessions#destroy", as: :destroy_session
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  validates :todo_text, presence: true
  validates :todo_text, length: { minimum: 2}
  validates :due_date, presence: true

  belongs_to :user

  def to_pleasant_string
    is_completed = completed ? "[x]" : "[ ]"
    return "#{id}. #{due_date.to_s(:short)} - #{todo_text} #{is_completed} "
  end

  def self.of_user(user)
    Todo.all.where(user_id: user.id)
  end

  def self.delete_todo(todo_id)
    Todo.delete(todo_id)
  end

  def self.due_today
    Todo.where("due_date = ? ",  Date.today)
  end

  def self.due_later
    Todo.where("due_date > ? ",  Date.today)
  end

  def self.over_due
    Todo.where("due_date < ? ", Date.today)
  end

  def show_due_date?
    return due_date != Date.today
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :todos
  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :ensure_user_logged_in

  def ensure_user_logged_in
    unless current_user
      redirect_to "/"
    end
  end

  def current_user
    return @current_user if @current_user

    current_user_id = session[:current_user_id]

    if current_user_id
      @current_user = User.find(current_user_id)
    else
      nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def index
    if current_user
      redirect_to todos_path
    else
      render "index"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_user_logged_in, only: [:new, :create]

  def new
    render "index"
  end

  def create
    user = User.find_by(email: params[:email])&.authenticate(params[:password])
    if user
      session[:current_user_id] = user.id
      redirect_to todos_path
    else
      flash[:error] = "Invalid email/password!"
      redirect_to new_sessions_path
    end
  end

  def destroy
    session[:current_user_id] = nil
    @current_user = nil
    redirect_to "/"
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @todos = Todo.of_user(current_user)
    render "index"
  end

  def show
    id = params[:id].to_i
    todo = Todo.find(id)
    render plain: todo.to_pleasant_string
  end

  def create
    new_todo = Todo.new(
      "todo_text": params[:todo_text],
      "due_date": params[:due_date],
      "completed": false,
      "user_id": current_user.id
    )

    if new_todo.save
      redirect_to todos_path
    else
      flash[:error] = new_todo.errors.full_messages.join(", ")
      redirect_to todos_path
    end
  end

  def update
    id = params[:id]
    completed = params[:completed]

    todo = Todo.of_user(current_user).find(id)
    todo.completed = completed
    todo.save

    redirect_to todos_path
  end

  def destroy
    id = params[:id]
    del = Todo.of_user(current_user).delete_todo(id)

    redirect_to todos_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_user_logged_in, only: [:new, :create]

  def new
    render "index"
  end

  def create
    User.create!(
      first_name: params[:first_name],
      last_name: params[:last_name],
      email: params[:email],
      password: params[:password]
    )

    redirect_to "/"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Welcome to Todos home page</h1>

<%= link_to "Sign in", new_sessions_path %>
<%= link_to "Register", new_user_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTodoManagerApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%if flash[:error]%>
    <p class="flash-error">
      <%= flash[:error]%>
    </p>
  <% end %>

  <%if @current_user%>
    <div class="user-container">
      <p class="user-name-heading">Welcome: <%= @current_user.first_name %>  </p>

      <%= link_to "Sign out", destroy_session_path, method: :delete, class: "primary-btn" %>

    </div>
  <% end %>

    <%= yield %>
  </body>
</html>

app/views/todos/_todos.html.erb
<h2><%= name%></h2>
<ul>
  <% todos.each do |todo| %>
    <li class="todo">

      <%= form_with url: "/todos/#{todo.id}", method: :put do %>
        <%= check_box_tag :completed, "completed", todo.completed ? true : false, onclick: "this.form.submit()"  %>
      <% end %>

      <p class="">
        <%= todo.id %>
      </p>

      <p class="todo-text <%= todo.completed ? 'strike' : '' %>">
        <%= todo.todo_text %>
      </p>

      <% if todo.show_due_date? %>
        <small class="due-date">
          <%= todo.due_date.to_s(:short) %>
        </small>
      <% end %>

      <%= form_with url: "todos/#{todo.id}", method: :delete do %>
        <%= button_tag :Delete, type: "submit" %>
      <% end %>

    </li>
  <% end %>
</ul>

app/views/todos/index.html.erb
<h1>This is todos list</h1>

<h2>Todos: <%= Todo.count%> </h2>

<%= form_with url: "/todos", method: :post do%>
  <input type="text" name="todo_text" placeholder="Type todo here...">
  <input type="date" name="due_date">
  <button type="submit" class="primary-btn"> Add </button>
<% end %>

<%= render partial: "todos", locals: {name: "Over Due", todos: @todos.over_due} %>
<%= render partial: "todos", locals: {name: "Due today", todos: @todos.due_today} %>
<%= render partial: "todos", locals: {name: "Due Later", todos: @todos.due_later} %>

app/views/users/index.html.erb
<h1>Register</h1>

<section class="Form-Container">

  <%= form_with url: users_path, method: :post do |form| %>
    <div class="Form-section">
      <p>First name: </p>
      <%= form.text_field :first_name, class: "Form-Input" %>
    </div>

    <div class="Form-section">
      <p>last name: </p>
      <%= form.text_field :last_name, class: "Form-Input" %>
    </div>

    <div class="Form-section">
      <p>Email: </p>
      <%= form.email_field :email, class: "Form-Input" %>
    </div>

    <div class="Form-section">
      <p>Password: </p>
      <%= form.password_field :password, class: "Form-Input" %>
    </div>

    <%= form.submit :Register, class: "primary-btn" %>

  <% end %>

</section>

<%= link_to "Sign in", new_sessions_path %>